#!/usr/bin/env python

import argparse

from nexp.clients.all import Clients
from nexp.tasks.send_candidate_lists import SendCandidateLists
from nexp.tasks.send_needs_requests import SendNeedsRequests


def send_candidate_lists(dryrun: bool) -> None:
    return SendCandidateLists(Clients(), dryrun)()


def send_needs_requests(dryrun: bool) -> None:
    return SendNeedsRequests(Clients(), dryrun)()


def main() -> None:
    parser = argparse.ArgumentParser(description="NEXP Backend")
    parser.add_argument("command", nargs=1)
    parser.add_argument("-d", "--dryrun", action="store_true", default=False)
    args = parser.parse_args()

    command = args.command[0]

    run = {
        "send-candidate-lists": send_candidate_lists,
        "send-needs-requests": send_needs_requests,
    }.get(command)

    if not run:
        print(f"'{command}' is not a valid command")
        exit(1)

    run(args.dryrun)


if __name__ == "__main__":
    main()
